// Import a real circuit GPS trace (GeoJSON LineString, [lon, lat] pairs — e.g. bacinger/f1-circuits) and
// emit a src/data/tracks/<id>.ts layout file (#sim-overhaul phase 6).
//
//   npx tsx scripts/track-import.ts <geojson-file> <circuitId> [--sf <lat,lon>] [--dir cw|ccw]
//
// Projection: equirectangular about the track's mean latitude, y flipped (north = up), scaled to fit the
// target box. --dir enforces race direction (default cw); the trace is reversed if drawn the other way.
// --sf rotates the loop so it starts at the vertex nearest the given lat,lon — path progress 0 is the S/F
// line, so anchor it on the pit straight. scripts/track-import-all.ts batch-runs this for the calendar.

import { readFileSync, writeFileSync } from 'fs'

const MAX_W = 480
const MAX_H = 440

export interface ImportOptions {
  /** S/F anchor as [lat, lon]; the loop is rotated to start at the nearest vertex. */
  sf?: [number, number]
  /** Race direction, viewed north-up. */
  dir?: 'cw' | 'ccw'
}

/** Convert a parsed GeoJSON FeatureCollection into the generated track-file source. */
export function trackFileContent(geo: unknown, circuitId: string, { sf, dir = 'cw' }: ImportOptions, sourceName: string): string {
  const g = geo as { features?: Array<{ properties?: { length?: number }; geometry?: { type?: string; coordinates?: number[][] } }> }
  const geom = g.features?.[0]?.geometry
  if (geom?.type !== 'LineString' || !geom.coordinates) throw new Error(`${circuitId}: expected a LineString, got ${geom?.type}`)
  const lengthM = g.features?.[0]?.properties?.length ?? 0
  if (!lengthM) throw new Error(`${circuitId}: geojson has no circuit length (features[0].properties.length, metres)`)

  let coords: [number, number][] = geom.coordinates.map((c) => [c[0], c[1]])
  const same = (a: [number, number], b: [number, number]) => a[0] === b[0] && a[1] === b[1]
  if (coords.length > 1 && same(coords[0], coords[coords.length - 1])) coords = coords.slice(0, -1)

  // Project: x = lon scaled by cos(mean lat) so metres match in both axes, y = -lat (north up).
  const lat0 = coords.reduce((s, c) => s + c[1], 0) / coords.length
  const kx = Math.cos((lat0 * Math.PI) / 180)
  let pts = coords.map(([lon, lat]) => ({ x: lon * kx, y: -lat }))

  // Enforce race direction. In y-down screen coords a positive shoelace sum = clockwise.
  const area = pts.reduce((s, p, i) => {
    const q = pts[(i + 1) % pts.length]
    return s + (p.x * q.y - q.x * p.y)
  }, 0)
  if ((dir === 'cw' && area < 0) || (dir === 'ccw' && area > 0)) pts = pts.slice().reverse()

  // Start the loop at the vertex nearest the S/F anchor.
  if (sf) {
    const anchor = { x: sf[1] * kx, y: -sf[0] }
    let best = 0
    let bestD = Infinity
    pts.forEach((p, i) => {
      const d = (p.x - anchor.x) ** 2 + (p.y - anchor.y) ** 2
      if (d < bestD) { bestD = d; best = i }
    })
    pts = [...pts.slice(best), ...pts.slice(0, best)]
  }

  // Normalise into the target box.
  const xs = pts.map((p) => p.x)
  const ys = pts.map((p) => p.y)
  const minX = Math.min(...xs), maxX = Math.max(...xs)
  const minY = Math.min(...ys), maxY = Math.max(...ys)
  const scale = Math.min(MAX_W / (maxX - minX), MAX_H / (maxY - minY))
  const w = Math.round((maxX - minX) * scale)
  const h = Math.round((maxY - minY) * scale)
  const r1 = (n: number) => Math.round(n * 10) / 10
  const trace = pts.map((p) => [r1((p.x - minX) * scale), r1((p.y - minY) * scale)])

  return `// Generated by scripts/track-import.ts from ${sourceName} (bacinger/f1-circuits). Do not hand-edit.

import type { TrackTrace } from '@/lib/ui/track-path'

export const TRACK: { viewBox: string; trace: TrackTrace; lengthM: number } = {
  viewBox: '0 0 ${w} ${h}',
  trace: ${JSON.stringify(trace)},
  lengthM: ${lengthM},
}
`
}

// ── CLI ──
if (process.argv[1]?.endsWith('track-import.ts')) {
  const [, , file, circuitId, ...rest] = process.argv
  if (!file || !circuitId) {
    console.error('usage: npx tsx scripts/track-import.ts <geojson-file> <circuitId> [--sf lat,lon] [--dir cw|ccw]')
    process.exit(1)
  }
  const argOf = (flag: string) => {
    const i = rest.indexOf(flag)
    return i >= 0 ? rest[i + 1] : undefined
  }
  const sfArg = argOf('--sf')
  const geo = JSON.parse(readFileSync(file, 'utf8'))
  const content = trackFileContent(geo, circuitId, {
    sf: sfArg ? (sfArg.split(',').map(Number) as [number, number]) : undefined,
    dir: (argOf('--dir') as 'cw' | 'ccw') ?? 'cw',
  }, file.replace(/\\/g, '/').split('/').pop() ?? file)
  const outPath = `src/data/tracks/${circuitId}.ts`
  writeFileSync(outPath, content)
  console.log(`${outPath} written`)
}
